// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiH8R-KLPGK9citDqs7rAV2f4kXmqA25w',
    appId: '1:1080723461432:web:7c53f009d003a16514ddcd',
    messagingSenderId: '1080723461432',
    projectId: 'metacolhub',
    authDomain: 'metacolhub.firebaseapp.com',
    storageBucket: 'metacolhub.appspot.com',
    measurementId: 'G-TNBPZ4Q8ET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGP1F_ZT0AibKMaH3PlTiWls438OgfUis',
    appId: '1:1080723461432:android:047645921e62f7d814ddcd',
    messagingSenderId: '1080723461432',
    projectId: 'metacolhub',
    storageBucket: 'metacolhub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA56D1vIkwTj8Kg25rQ1idjfsl4ScmxG7Y',
    appId: '1:1080723461432:ios:7f49bd954842ce2514ddcd',
    messagingSenderId: '1080723461432',
    projectId: 'metacolhub',
    storageBucket: 'metacolhub.appspot.com',
    iosBundleId: 'com.example.metaColHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA56D1vIkwTj8Kg25rQ1idjfsl4ScmxG7Y',
    appId: '1:1080723461432:ios:7f49bd954842ce2514ddcd',
    messagingSenderId: '1080723461432',
    projectId: 'metacolhub',
    storageBucket: 'metacolhub.appspot.com',
    iosBundleId: 'com.example.metaColHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiH8R-KLPGK9citDqs7rAV2f4kXmqA25w',
    appId: '1:1080723461432:web:439a902cea7bfc3e14ddcd',
    messagingSenderId: '1080723461432',
    projectId: 'metacolhub',
    authDomain: 'metacolhub.firebaseapp.com',
    storageBucket: 'metacolhub.appspot.com',
    measurementId: 'G-W25K9MDPJL',
  );
}
